bash yahooNews.sh "Happy Opening Day"
bash yahooNews.sh "Cubs"
bash yahooNews.sh "Cardinals"
bash yahooNews.sh "#youknowyourefromtwitterwhen"
bash yahooNews.sh "#askissues"
bash yahooNews.sh "#5thTimesACharm5H"
bash yahooNews.sh "Tomorrow is April"
bash yahooNews.sh "#ballhr5"
bash yahooNews.sh "#BrewersOpener"
bash yahooNews.sh "Strasburg"
bash yahooNews.sh "St. Louis"
