cat "trends/Happy Opening Day.txt"
cat "trends/Ryan Braun.txt"
cat "trends/Cubs.txt"
cat "trends/#STLCards.txt"
cat "trends/Cardinals.txt"
cat "trends/World Series.txt"
cat "trends/St. Louis.txt"
cat "trends/#RipZaynMalik.txt"
cat "trends/#IfTwitterExistedInHistory.txt"
cat "trends/#AndreaTo1Milli.txt"
cat "trends/St. Louis.txt"
