wget "https://news.google.com/?q=HiCam" -O "Trends/HiCam.txt" -o /dev/null
wget "https://news.google.com/?q=RuinACartoon" -O "Trends/RuinACartoon.txt" -o /dev/null
wget "https://news.google.com/?q=HIMYMFinale" -O "Trends/HIMYMFinale.txt" -o /dev/null
wget "https://news.google.com/?q=Tiger Woods" -O "Trends/Tiger Woods.txt" -o /dev/null
wget "https://news.google.com/?q=How I Met Your Mother" -O "Trends/How I Met Your Mother.txt" -o /dev/null
wget "https://news.google.com/?q=Mike Trout" -O "Trends/Mike Trout.txt" -o /dev/null
wget "https://news.google.com/?q=Will Smith" -O "Trends/Will Smith.txt" -o /dev/null
wget "https://news.google.com/?q=Taco Bell" -O "Trends/Taco Bell.txt" -o /dev/null
wget "https://news.google.com/?q=Kenny Britt" -O "Trends/Kenny Britt.txt" -o /dev/null
wget "https://news.google.com/?q=Starbucks" -O "Trends/Starbucks.txt" -o /dev/null
wget "https://news.google.com/?q=St. Louis" -O "Trends/St. Louis.txt" -o /dev/null
